-- lite-xl 1.16
local syntax = require "core.syntax"

syntax.add {
  files = { "%.cmd$" },
  -- headers = "^#!.*bin.*sh\n",
  comment = "#",
  patterns = {
    { pattern = "#split",       type = "keyword2"  },
    { pattern = "#if",       type = "keyword2"  },
    { pattern = "#end%a+",       type = "keyword2"  },
    { pattern = "#header",       type = "keyword2"  },
    { pattern = "#postheader",       type = "keyword2"  },
    { pattern = "#.*\n",                  type = "comment"  },
    { pattern = "$[%a_@*][%w_]*",         type = "function" },
    { pattern = "${[%a_@*][%w_]*}",       type = "function" },
    { pattern = "[{}]",                 type = "number" },
    { pattern = "[%[%]]",                 type = "keyword" },
    { pattern = "@[%a_][%w_]*@",          type = "function"   },
    { pattern = "[%a_][%w_]*",            type = "symbol"   },
 },
  symbols = {
    ["foreach"]  = "keyword",
    ["set"]      = "keyword",
    ["proc"]     = "keyword",
    ["if"]       = "keyword",
    ["then"]       = "keyword",
    ["elseif"]       = "keyword",
    ["else"]       = "keyword",
    ["return"]       = "keyword",
    ["break"]       = "keyword",
    ["expr"]       = "keyword",
    ["eval"]       = "keyword",
    ["concat"]   = "string",
    ["lindex"]   = "string",
    ["lsearch"]   = "string",
    ["llength"]   = "string",
    ["lappend"]   = "string",
    ["linsert"]   = "string",
    ["lrange"]   = "string",
    ["lsort"]   = "string",
    ["list"]   = "string",
    ["lreplace"]   = "string",
    ["fset"]     = "keyword",
    ["fproc"]    = "keyword",
    ["package"] = "literal",
    ["refinebox"] = "literal",
    ["mgoals"] = "literal",
    ["mater"] = "literal",
    ["pdbSet"]   = "keyword2",
    ["pdbSetDouble"]   = "keyword2",
    ["Arsenic"] = "number",
    ["Boron"] = "number",
    ["Silicon"] = "number",
    ["Phosphorus"] = "number",
    ["Indium"] = "number",
    ["PolySilicon"] = "number",
    ["Oxide"] = "number",
    ["Nitride"] = "number",
    ["temp_ramp"] = "keyword",
    ["etch"] = "keyword",
    ["deposit"] = "keyword",
    ["diffuse"] = "keyword",
    ["strip"] = "keyword",
    ["photo"] = "keyword",
    ["implant"] = "keyword",
    ["struct"] = "keyword",
  },
}

